name: Build branch

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Java'
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 17
    - name: Build
      run: ./gradlew build --stacktrace
